# Generated by Django 5.2.2 on 2026-03-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('pricing', models.CharField(choices=[('free', 'Free'), ('freemium', 'Free tier available'), ('paid', 'Paid only')], default='paid', max_length=20)),
                ('color', models.CharField(default='slate', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='prompt',
            name='compatible_tools',
            field=models.ManyToManyField(blank=True, related_name='prompts', to='prompts.aitool'),
        ),
    ]
