# Generated by Django 5.2.2 on 2026-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_prompt_forked_from_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='icon',
            field=models.CharField(default='', max_length=10),
        ),
    ]
